# You can set the hostname of docker host by using this command `sudo hostname <name>`
version: "3"
services:

  nserver:
    image: cloudwattfr/ntpserver:latest
    ports:
      - 2200:2200
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == cluster0]
    privileged: true

  viv:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.VivaldiApp
      - ARGS=--port 2549 --ip viv
    depends_on:
      - nserver
    ports:
      - 2549:2549
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == cluster0]
    privileged: true

  gui:
    image: tcep-gui
    ports:
       - 3000:3000
    networks:
       - main
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
      placement:
        constraints: [node.hostname == cluster0]
    privileged: true

  simulator:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.simulation.tcep.SimulationRunner
      - ARGS= ./logs 4 simulator 2202
    depends_on:
       - viv
    volumes:
       - $HOME/logs:/app/logs
    ports:
       - 2202:2202
       - 25001:25001
    networks:
       - main
    deploy:
      replicas: 1
      restart_policy:
         condition: on-failure
      placement:
        constraints: [node.hostname == cluster0]
    privileged: true

  DoorSensor:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--port 3300 --name DoorSensor --ip DoorSensor --host cluster1
    depends_on:
      - viv
    ports:
      - 3300:3300
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == cluster1]
    privileged: true

  SanitizerSensor:
    image: ocastx/tcep
    environment:
      - MAIN=tcep.machinenodes.PublisherApp
      - ARGS=--port 3301 --name SanitizerSensor --ip SanitizerSensor --host cluster2
    depends_on:
      - viv
    ports:
      - 3301:3301
    volumes:
      - $HOME/logs:/app/logs
    networks:
      - main
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == cluster2]
    privileged: true


networks:
  main: